P2642R1: Start work
ORNL/cpp-proposals-pub pull request #298
Opened 2022-09-28 21:57 UTC by mhoemmen

* Fix typos in Wording
* Fix formatting in non-Wording
* Improve explanation of progress on implementation

2022-10-14 04:30 UTC, mhoemmen commented on layout_padded/layout_padded.bs
> +    and <a href="https://netlib.org/lapack/">LAPACK</a>; and
@dalg24 Thanks for the suggestion!  I've applied this change.

2022-10-14 16:06 UTC, crtrott commented
Thinking through the conversion stuff assignment:

`layout_left_padded<dynamic_extent>::mapping (extents(9,2),12)` -> this stores stride 12, padding_stride is 12

- `layout_left_padded<4>` -> `layout_left_padded<4>`
  - fine? Yes because (runtime) extents stay the same: so if src was 'legal' then dest is good, even if extents type changes 
- `layout_left_padded<4>` -> `layout_left_padded<2>` 
  - may not be fine: say extent was 9x2 before leading to physical layout of  12x2, but layout_left_padded<2> implies 10x2
  - `layout_left_padded<4>::mapping(extents(9,2)).stride(1) == 12`
  - `layout_left_padded<2>::mapping(extents(9,2)).stride(1) == 10`
  - thats why we should not be allowed to assign mismatching static paddings
- when assigning dynamic `padding_stride` to static `padding_stride`: precondition on matching.

2022-10-14 21:27 UTC, mhoemmen commented
@crtrott I've added a nonwording section that expands on your example above.  This PR should be ready to merge now.  Thanks!

2022-10-14 21:41 UTC, mhoemmen commented
@crtrott @dalg24 @nliber I've submitted this version as P2642R1.  Thanks all for the great feedback!

2022-10-14 22:49 UTC, crtrott requested changes
More notes:
  - layout_left_padded -> layout_left 
      - don’t need to check destination static extent: mandate that other_padding_stride = otherExtents.static_extent(0) is enough. Everything else is already covered by the constraint
      - don’t need this “If OtherExtents::rank() is greater than one, then other.stride(1) is representable as a value of type index_type;” covered by required span size
  - padding_stride needs to be larger 0 mandate
  - P_left be the following size extents_type::rank() “-1” missing
- Do we need a way to get padding_stride: maybe static_padding_stride()
- Copy construction from layout_left/right or maybe even any strided layout?
- operator() needs to return index_type

2022-10-17 03:40 UTC, mhoemmen commented on layout_padded/layout_padded.bs
> +* if `extents_type::rank() > 0` is `true`, then for all $r$ in the range [0, `extents_type::rank()`), `other.stride(` $r$ `)` equals `extents().`_`fwd-prod-of-extents`_`(` $r$ `)`, and
@crtrott wrote:
> `// can you do the following (note char)?? We wouldn't be able to store overalignment factor`
> `layout_left_padded<dynamic_extent>::mapping<extents<char,dynamic_extent,dynamic_extent>> dest = src;`

This should be a precondition violation.  I would like this to have the analogous precondition to `extents`'s converting constructor ([[mdspan.extents.cons]](http://eel.is/c++draft/mdspan.extents.cons)).

> `// can you do this?? What if we don't store overalignment factor:`
> `layout_left_padded<1024>::mapping<dextents<int,2>> dest = src;`

This should be legal.  (Did you mean to write `dextents<char, 2>` in there?)

> `layout_left_padded<1024>::mapping<dextents<int8_t, 2>> dest = src;`

This should _not_ be legal.  I think I made this a Mandate.  If it's not, it should be.

> `// or is this legal??`
> `layout_left_padded<0>::mapping<dextents<int,2>> dest = src;`

This should _not_ be legal, for different reasons.  `layout_{left,right}_padded::mapping` is a special case of `layout_stride::mapping`, so the requirement that all the strides be positive should apply: [[mdspan.layout.stride.cons]](http://eel.is/c++draft/mdspan.layout.stride.cons).  I should make this a Mandate if static, and a Precondition if not.

2022-12-28 17:58 UTC, merged